In [1]:
import numpy as np
import pandas as pd
dataset=pd.read_csv("acquisitions.csv")

In [2]:
dataset

,AcquisitionID,AcquisitionMonth,AcquisitionMonthDate,AcquisitionYear,Company,Business,Country,Value (USD),Derived products,ParentCompany
0,ACQ99,November,11.0,2015,bebop,Cloud software,USA,3.800000e+08,Google Cloud Platform,Google
1,ACQ98,November,11.0,2015,Fly Labs,Video editing,USA,NaN,Google Photos,Google
2,ACQ97,December,8.0,2015,Clearleap,Cloud-based video management,USA,NaN,NaN,IBM
3,ACQ96,December,18.0,2015,Metanautix,Big Data Analytics,USA,NaN,NaN,Microsoft
4,ACQ95,December,21.0,2015,"Talko, Inc.",Mobile communications,USA,NaN,NaN,Microsoft
5,ACQ94,January,7.0,2016,Emotient,Emotion recognition,USA,NaN,"Face ID, Animoji[100]",Apple
6,ACQ93,January,15.0,2016,Iris Analytics,Real time transaction fraud detection,GER,NaN,NaN,IBM
7,ACQ92,January,19.0,2016,Teacher Gaming LLC,Education software,FIN,NaN,NaN,Microsoft
8,ACQ915,July,30.0,1987,"Forethought, Inc.",Computer software,USA,1.400000e+07,NaN,Microsoft
9,ACQ914,March,2.0,1988,Network Innovations,Software,USA,NaN,NaN,Apple
10,ACQ913,June,7.0,1988,Orion Network Systems,Satellite communication systems,USA,NaN,NaN,Apple
11,ACQ912,June,27.0,1988,Styleware,Computer software,USA,NaN,AppleWorks GS,Apple
12,ACQ911,July,11.0,1988,Claris,Computer software,USA,NaN,"FileMaker, iWork, iLife",Apple
13,ACQ910,January,3.0,1989,Coral Software,Computer software,USA,NaN,Macintosh Common Lisp,Apple
14,ACQ91,January,21.0,2016,Ustream,Streaming video,USA,NaN,NaN,IBM
15,ACQ909,March,31.0,1991,Consumers Software,Software,CAN,NaN,NaN,Microsoft
16,ACQ908,June,29.0,1992,Fox Software,PC database software,USA,NaN,NaN,Microsoft
17,ACQ907,February,28.0,1994,Softimage,Wholesale 3-D visualization software,CAN,NaN,NaN,Microsoft
18,ACQ906,September,27.0,1994,Altamira Software,Software,USA,NaN,NaN,Microsoft
19,ACQ905,November,1.0,1994,NextBase,Software,USA,NaN,NaN,Microsoft
20,ACQ904,November,15.0,1994,One Tree Software,Software,USA,NaN,NaN,Microsoft
21,ACQ903,February,23.0,1995,RenderMorphics,3D graphics hardware,USA,NaN,NaN,Microsoft
22,ACQ902,July,10.0,1995,Network Managers,Systems design,UK,NaN,NaN,Microsoft
23,ACQ901,October,17.0,1995,The Blue Ribbon SoundWorks,Software,USA,NaN,NaN,Microsoft
24,ACQ900,November,6.0,1995,Netwise,Computer software,USA,NaN,NaN,Microsoft
25,ACQ90,January,28.0,2016,LearnSprout,Education technology,USA,NaN,Classroom iPad App,Apple
26,ACQ9,October,16.0,2017,tbh,Anonymous social media app,USA,NaN,NaN,Facebook
27,ACQ899,December,12.0,1995,Bruce Artwick Organization,Programming,USA,NaN,NaN,Microsoft
28,ACQ898,January,16.0,1996,Vermeer Technologies,Software,USA,1.330000e+08,NaN,Microsoft
29,ACQ897,March,6.0,1996,VGA-Animation Software Div[note 1],Software,GER,NaN,NaN,Microsoft
...,...,...,...,...,...,...,...,...,...,...
886,ACQ124,July,23.0,2015,Compose Inc.,Database as a Service,USA,NaN,NaN,IBM
887,ACQ123,July,31.0,2015,Polyvore,Clothing E-commerce website,USA,1.600000e+08,NaN,Yahoo
888,ACQ122,August,3.0,2015,"Incent Games, LLC",Sales-gamification,USA,NaN,NaN,Microsoft
889,ACQ121,August,6.0,2015,Merge Healthcare Inc.,Healthcare imaging software,USA,1.000000e+09,NaN,IBM
890,ACQ120,September,NaN,2015,Perceptio,"Machine learning, Image recognition",USA,NaN,"Face ID, Animoji, Photos",Apple
891,ACQ12,October,5.0,2017,Vivant Digital,Innovation Consultancy,AUS,NaN,NaN,IBM
892,ACQ119,September,NaN,2015,VocalIQ,Speech technology,UK,NaN,Siri,Apple
893,ACQ118,September,NaN,2015,Mapsense,Mapping visualization and data collection,USA,NaN,Apple Maps,Apple
894,ACQ117,September,3.0,2015,"VoloMetrix, Inc.",Organisational analytics,USA,NaN,NaN,Microsoft
895,ACQ116,September,10.0,2015,StrongLoop Inc.,Mobile API capabilities,USA,NaN,NaN,IBM
896,ACQ115,September,11.0,2015,"Double Labs, Inc.",Mobile lock screen software,USA,NaN,NaN,Microsoft
897,ACQ114,September,21.0,2015,Oyster,E-book subscriptions,USA,NaN,Google Play Books,Google
898,ACQ113,September,28.0,2015,Adxstudio Inc.,Web portal and application lifecycle managemen...,CAN,NaN,NaN,Microsoft
899,ACQ112,September,28.0,2015,Meteorix LLC,Consulting services for Workday applications,USA,NaN,NaN,IBM
900,ACQ111,September,30.0,2015,Jibe Mobile,Rich Communication Services,USA,NaN,Android,Google
901,ACQ110,October,2.0,2015,Telekinesys Research Ltd.,Game technology vendor,IRL,NaN,NaN,Microsoft
902,ACQ11,October,9.0,2017,Relay Media,AMP converter,USA,NaN,Accelerated Mobile Pages,Google
903,ACQ109,October,3.0,2015,Endaga,Rural communications,USA,NaN,NaN,Facebook
904,ACQ108,October,17.0,2015,Digisfera,360-degree photography,POR,NaN,Street View,Google
905,ACQ107,October,21.0,2015,ZeroPush,Push Notification Services,USA,NaN,NaN,Twitter
906,ACQ106,October,21.0,2015,Fastlane,Deployment Services,NaN,NaN,NaN,Twitter
907,ACQ105,October,28.0,2015,The Weather Company digital assets,"Weather data sources and analytics, related on...",USA,NaN,NaN,IBM
908,ACQ104,November,NaN,2015,Faceshift,Realtime Motion Capture,SWI,NaN,Animoji,Apple
909,ACQ103,November,3.0,2015,"Gravitant, Inc",Cloud brokerage software and cloud management,USA,NaN,NaN,IBM
910,ACQ102,November,5.0,2015,"Mobile Data Labs, Inc.","MileIQ, a mileage tracking application",USA,NaN,NaN,Microsoft
911,ACQ101,November,6.0,2015,Cleversafe,Object-based storage software,USA,1.309000e+09,NaN,IBM
912,ACQ100,November,9.0,2015,Secure Islands Technologies Ltd.,Data protection,ISR,NaN,NaN,Microsoft
913,ACQ10,October,11.0,2017,60db,Podcasts,USA,NaN,Google Play Music,Google
914,ACQ1,May,18.0,2018,Semantic Machines,Conversational AI,USA,NaN,NaN,Microsoft
915,AcQ916,June,4.0,2018,Github,Version Control Hosting,USA,7.500000e+09,NaN,Microsoft

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.head()

,AcquisitionID,AcquisitionMonth,AcquisitionMonthDate,AcquisitionYear,Company,Business,Country,Value (USD),Derived products,ParentCompany
0,ACQ99,November,11.0,2015,bebop,Cloud software,USA,380000000.0,Google Cloud Platform,Google
1,ACQ98,November,11.0,2015,Fly Labs,Video editing,USA,NaN,Google Photos,Google
2,ACQ97,December,8.0,2015,Clearleap,Cloud-based video management,USA,NaN,NaN,IBM
3,ACQ96,December,18.0,2015,Metanautix,Big Data Analytics,USA,NaN,NaN,Microsoft
4,ACQ95,December,21.0,2015,"Talko, Inc.",Mobile communications,USA,NaN,NaN,Microsoft

In [5]:
dataset.shape

(916, 10)

In [6]:
dataset.isnull().sum()

AcquisitionID             0
AcquisitionMonth          6
AcquisitionMonthDate     33
AcquisitionYear           0
Company                   0
Business                  0
Country                  46
Value (USD)             671
Derived products        515
ParentCompany             0
dtype: int64

In [7]:
data1=dataset.iloc[:,[0,1,3,5,6,7,9]]

In [8]:
data1

,AcquisitionID,AcquisitionMonth,AcquisitionYear,Business,Country,Value (USD),ParentCompany
0,ACQ99,November,2015,Cloud software,USA,3.800000e+08,Google
1,ACQ98,November,2015,Video editing,USA,NaN,Google
2,ACQ97,December,2015,Cloud-based video management,USA,NaN,IBM
3,ACQ96,December,2015,Big Data Analytics,USA,NaN,Microsoft
4,ACQ95,December,2015,Mobile communications,USA,NaN,Microsoft
5,ACQ94,January,2016,Emotion recognition,USA,NaN,Apple
6,ACQ93,January,2016,Real time transaction fraud detection,GER,NaN,IBM
7,ACQ92,January,2016,Education software,FIN,NaN,Microsoft
8,ACQ915,July,1987,Computer software,USA,1.400000e+07,Microsoft
9,ACQ914,March,1988,Software,USA,NaN,Apple
10,ACQ913,June,1988,Satellite communication systems,USA,NaN,Apple
11,ACQ912,June,1988,Computer software,USA,NaN,Apple
12,ACQ911,July,1988,Computer software,USA,NaN,Apple
13,ACQ910,January,1989,Computer software,USA,NaN,Apple
14,ACQ91,January,2016,Streaming video,USA,NaN,IBM
15,ACQ909,March,1991,Software,CAN,NaN,Microsoft
16,ACQ908,June,1992,PC database software,USA,NaN,Microsoft
17,ACQ907,February,1994,Wholesale 3-D visualization software,CAN,NaN,Microsoft
18,ACQ906,September,1994,Software,USA,NaN,Microsoft
19,ACQ905,November,1994,Software,USA,NaN,Microsoft
20,ACQ904,November,1994,Software,USA,NaN,Microsoft
21,ACQ903,February,1995,3D graphics hardware,USA,NaN,Microsoft
22,ACQ902,July,1995,Systems design,UK,NaN,Microsoft
23,ACQ901,October,1995,Software,USA,NaN,Microsoft
24,ACQ900,November,1995,Computer software,USA,NaN,Microsoft
25,ACQ90,January,2016,Education technology,USA,NaN,Apple
26,ACQ9,October,2017,Anonymous social media app,USA,NaN,Facebook
27,ACQ899,December,1995,Programming,USA,NaN,Microsoft
28,ACQ898,January,1996,Software,USA,1.330000e+08,Microsoft
29,ACQ897,March,1996,Software,GER,NaN,Microsoft
...,...,...,...,...,...,...,...
886,ACQ124,July,2015,Database as a Service,USA,NaN,IBM
887,ACQ123,July,2015,Clothing E-commerce website,USA,1.600000e+08,Yahoo
888,ACQ122,August,2015,Sales-gamification,USA,NaN,Microsoft
889,ACQ121,August,2015,Healthcare imaging software,USA,1.000000e+09,IBM
890,ACQ120,September,2015,"Machine learning, Image recognition",USA,NaN,Apple
891,ACQ12,October,2017,Innovation Consultancy,AUS,NaN,IBM
892,ACQ119,September,2015,Speech technology,UK,NaN,Apple
893,ACQ118,September,2015,Mapping visualization and data collection,USA,NaN,Apple
894,ACQ117,September,2015,Organisational analytics,USA,NaN,Microsoft
895,ACQ116,September,2015,Mobile API capabilities,USA,NaN,IBM
896,ACQ115,September,2015,Mobile lock screen software,USA,NaN,Microsoft
897,ACQ114,September,2015,E-book subscriptions,USA,NaN,Google
898,ACQ113,September,2015,Web portal and application lifecycle managemen...,CAN,NaN,Microsoft
899,ACQ112,September,2015,Consulting services for Workday applications,USA,NaN,IBM
900,ACQ111,September,2015,Rich Communication Services,USA,NaN,Google
901,ACQ110,October,2015,Game technology vendor,IRL,NaN,Microsoft
902,ACQ11,October,2017,AMP converter,USA,NaN,Google
903,ACQ109,October,2015,Rural communications,USA,NaN,Facebook
904,ACQ108,October,2015,360-degree photography,POR,NaN,Google
905,ACQ107,October,2015,Push Notification Services,USA,NaN,Twitter
906,ACQ106,October,2015,Deployment Services,NaN,NaN,Twitter
907,ACQ105,October,2015,"Weather data sources and analytics, related on...",USA,NaN,IBM
908,ACQ104,November,2015,Realtime Motion Capture,SWI,NaN,Apple
909,ACQ103,November,2015,Cloud brokerage software and cloud management,USA,NaN,IBM
910,ACQ102,November,2015,"MileIQ, a mileage tracking application",USA,NaN,Microsoft
911,ACQ101,November,2015,Object-based storage software,USA,1.309000e+09,IBM
912,ACQ100,November,2015,Data protection,ISR,NaN,Microsoft
913,ACQ10,October,2017,Podcasts,USA,NaN,Google
914,ACQ1,May,2018,Conversational AI,USA,NaN,Microsoft
915,AcQ916,June,2018,Version Control Hosting,USA,7.500000e+09,Microsoft

In [9]:
data1.dropna(subset=['Value (USD)'], inplace = True)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [10]:
data1

,AcquisitionID,AcquisitionMonth,AcquisitionYear,Business,Country,Value (USD),ParentCompany
0,ACQ99,November,2015,Cloud software,USA,3.800000e+08,Google
8,ACQ915,July,1987,Computer software,USA,1.400000e+07,Microsoft
28,ACQ898,January,1996,Software,USA,1.330000e+08,Microsoft
32,ACQ894,April,1996,Computer software,USA,1.415000e+07,Microsoft
36,ACQ890,February,1997,Internet software,USA,2.000000e+07,Microsoft
38,ACQ889,February,1997,Unix-like hardware and software platform,USA,4.040000e+08,Apple
40,ACQ887,April,1997,Internet service provider,USA,4.250000e+08,Microsoft
45,ACQ882,September,1997,Web search engine,USA,1.400000e+06,Yahoo
46,ACQ881,September,1997,Macintosh clones,USA,1.100000e+08,Apple
47,ACQ880,October,1997,Web-based email,USA,9.200000e+07,Yahoo
49,ACQ879,December,1997,Internet software,USA,5.000000e+08,Microsoft
52,ACQ876,April,1998,Relationship management software,USA,4.000000e+07,Microsoft
55,ACQ873,June,1998,Web application,USA,4.860000e+07,Yahoo
56,ACQ872,July,1998,Calendaring software,USA,2.100000e+07,Yahoo
58,ACQ870,October,1998,Direct marketing,USA,2.960000e+07,Yahoo
60,ACQ869,November,1998,Internet advertising network,USA,2.650000e+08,Microsoft
61,ACQ868,December,1998,Data analysis,USA,8.100000e+06,Yahoo
62,ACQ867,January,1999,Software,UK,4.926000e+06,Apple
66,ACQ863,April,1999,Internet radio,USA,5.700000e+09,Yahoo
69,ACQ860,May,1999,Internet service provider,USA,1.300000e+08,Yahoo
70,ACQ86,February,2016,"SwiftKey, a keyboard productivity application",UK,2.500000e+08,Microsoft
71,ACQ859,May,1999,Web hosting service,USA,3.600000e+09,Yahoo
72,ACQ858,June,1999,Content delivery network,USA,8.000000e+07,Yahoo
75,ACQ855,June,1999,Defect detection software,USA,5.890000e+07,Microsoft
76,ACQ854,July,1999,Application software,SWE,1.254200e+08,Microsoft
82,ACQ849,November,1999,Computer graphic chips,USA,1.500000e+07,Apple
83,ACQ848,January,2000,Wholesale drawing software,USA,1.375000e+09,Microsoft
86,ACQ845,March,2000,Internet service provider,USA,8.975000e+07,Microsoft
90,ACQ841,April,2000,Cable television,USA,9.448000e+08,Microsoft
93,ACQ839,June,2000,E-commerce,USA,8.900000e+06,Yahoo
...,...,...,...,...,...,...,...
745,ACQ251,January,2014,Artificial intelligence,UK,6.250000e+08,Google
752,ACQ245,February,2014,Mobile messaging,USA,1.900000e+10,Facebook
758,ACQ24,June,2017,Cloud Business Management,ISR,5.000000e+07,Microsoft
759,ACQ239,March,2014,Virtual reality technology,USA,2.000000e+09,Facebook
760,ACQ238,March,2014,High-altitude UAVs,UK,2.000000e+07,Facebook
766,ACQ232,April,2014,Data reseller,NaN,1.340000e+08,Twitter
781,ACQ219,June,2014,Mobile app install ads,NaN,1.000000e+08,Twitter
782,ACQ218,June,2014,Native mobile advertising,NaN,5.000000e+07,Twitter
784,ACQ216,June,2014,Satellite,USA,5.000000e+08,Google
789,ACQ211,June,2014,Home monitoring,USA,5.550000e+08,Google
793,ACQ208,June,2014,Music streaming,USA,3.000000e+07,Apple
799,ACQ202,July,2014,Mobile Analytics,USA,2.000000e+08,Yahoo
806,ACQ197,August,2014,"Headphones, music streaming (Beats Music)",USA,3.000000e+09,Apple
814,ACQ19,September,2017,Talent and intellectual property licenses,TWN,1.100000e+09,Google
822,ACQ182,September,2014,Document Handling,IND,1.500000e+07,Yahoo
825,ACQ18,September,2017,Augmented reality head-mounted display,CAN,3.000000e+07,Apple
830,ACQ175,November,2014,Video games,SWE,2.500000e+09,Microsoft
831,ACQ174,November,2014,Online Video Advertising,USA,6.400000e+08,Yahoo
845,ACQ161,January,2015,Music analytics,UK,5.000000e+07,Apple
848,ACQ159,February,2015,Sunrise Calendar applications,USA,1.000000e+08,Microsoft
852,ACQ155,February,2015,Styli and pen input hardware and software,ISR,2.000000e+08,Microsoft
856,ACQ151,March,2015,Live-Video Streaming,NaN,1.000000e+08,Twitter
867,ACQ141,April,2015,Camera,ISR,2.000000e+07,Apple
871,ACQ138,April,2015,Advertising,NaN,4.790000e+08,Twitter
883,ACQ127,July,2015,"Computer vision, augmented reality",ISR,6.000000e+07,Facebook
884,ACQ126,July,2015,Cloud security,ISR,3.200000e+08,Microsoft
887,ACQ123,July,2015,Clothing E-commerce website,USA,1.600000e+08,Yahoo
889,ACQ121,August,2015,Healthcare imaging software,USA,1.000000e+09,IBM
911,ACQ101,November,2015,Object-based storage software,USA,1.309000e+09,IBM
915,AcQ916,June,2018,Version Control Hosting,USA,7.500000e+09,Microsoft

In [11]:
data1.Country.fillna('USA',inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5430: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [12]:
data1

,AcquisitionID,AcquisitionMonth,AcquisitionYear,Business,Country,Value (USD),ParentCompany
0,ACQ99,November,2015,Cloud software,USA,3.800000e+08,Google
8,ACQ915,July,1987,Computer software,USA,1.400000e+07,Microsoft
28,ACQ898,January,1996,Software,USA,1.330000e+08,Microsoft
32,ACQ894,April,1996,Computer software,USA,1.415000e+07,Microsoft
36,ACQ890,February,1997,Internet software,USA,2.000000e+07,Microsoft
38,ACQ889,February,1997,Unix-like hardware and software platform,USA,4.040000e+08,Apple
40,ACQ887,April,1997,Internet service provider,USA,4.250000e+08,Microsoft
45,ACQ882,September,1997,Web search engine,USA,1.400000e+06,Yahoo
46,ACQ881,September,1997,Macintosh clones,USA,1.100000e+08,Apple
47,ACQ880,October,1997,Web-based email,USA,9.200000e+07,Yahoo
49,ACQ879,December,1997,Internet software,USA,5.000000e+08,Microsoft
52,ACQ876,April,1998,Relationship management software,USA,4.000000e+07,Microsoft
55,ACQ873,June,1998,Web application,USA,4.860000e+07,Yahoo
56,ACQ872,July,1998,Calendaring software,USA,2.100000e+07,Yahoo
58,ACQ870,October,1998,Direct marketing,USA,2.960000e+07,Yahoo
60,ACQ869,November,1998,Internet advertising network,USA,2.650000e+08,Microsoft
61,ACQ868,December,1998,Data analysis,USA,8.100000e+06,Yahoo
62,ACQ867,January,1999,Software,UK,4.926000e+06,Apple
66,ACQ863,April,1999,Internet radio,USA,5.700000e+09,Yahoo
69,ACQ860,May,1999,Internet service provider,USA,1.300000e+08,Yahoo
70,ACQ86,February,2016,"SwiftKey, a keyboard productivity application",UK,2.500000e+08,Microsoft
71,ACQ859,May,1999,Web hosting service,USA,3.600000e+09,Yahoo
72,ACQ858,June,1999,Content delivery network,USA,8.000000e+07,Yahoo
75,ACQ855,June,1999,Defect detection software,USA,5.890000e+07,Microsoft
76,ACQ854,July,1999,Application software,SWE,1.254200e+08,Microsoft
82,ACQ849,November,1999,Computer graphic chips,USA,1.500000e+07,Apple
83,ACQ848,January,2000,Wholesale drawing software,USA,1.375000e+09,Microsoft
86,ACQ845,March,2000,Internet service provider,USA,8.975000e+07,Microsoft
90,ACQ841,April,2000,Cable television,USA,9.448000e+08,Microsoft
93,ACQ839,June,2000,E-commerce,USA,8.900000e+06,Yahoo
...,...,...,...,...,...,...,...
745,ACQ251,January,2014,Artificial intelligence,UK,6.250000e+08,Google
752,ACQ245,February,2014,Mobile messaging,USA,1.900000e+10,Facebook
758,ACQ24,June,2017,Cloud Business Management,ISR,5.000000e+07,Microsoft
759,ACQ239,March,2014,Virtual reality technology,USA,2.000000e+09,Facebook
760,ACQ238,March,2014,High-altitude UAVs,UK,2.000000e+07,Facebook
766,ACQ232,April,2014,Data reseller,USA,1.340000e+08,Twitter
781,ACQ219,June,2014,Mobile app install ads,USA,1.000000e+08,Twitter
782,ACQ218,June,2014,Native mobile advertising,USA,5.000000e+07,Twitter
784,ACQ216,June,2014,Satellite,USA,5.000000e+08,Google
789,ACQ211,June,2014,Home monitoring,USA,5.550000e+08,Google
793,ACQ208,June,2014,Music streaming,USA,3.000000e+07,Apple
799,ACQ202,July,2014,Mobile Analytics,USA,2.000000e+08,Yahoo
806,ACQ197,August,2014,"Headphones, music streaming (Beats Music)",USA,3.000000e+09,Apple
814,ACQ19,September,2017,Talent and intellectual property licenses,TWN,1.100000e+09,Google
822,ACQ182,September,2014,Document Handling,IND,1.500000e+07,Yahoo
825,ACQ18,September,2017,Augmented reality head-mounted display,CAN,3.000000e+07,Apple
830,ACQ175,November,2014,Video games,SWE,2.500000e+09,Microsoft
831,ACQ174,November,2014,Online Video Advertising,USA,6.400000e+08,Yahoo
845,ACQ161,January,2015,Music analytics,UK,5.000000e+07,Apple
848,ACQ159,February,2015,Sunrise Calendar applications,USA,1.000000e+08,Microsoft
852,ACQ155,February,2015,Styli and pen input hardware and software,ISR,2.000000e+08,Microsoft
856,ACQ151,March,2015,Live-Video Streaming,USA,1.000000e+08,Twitter
867,ACQ141,April,2015,Camera,ISR,2.000000e+07,Apple
871,ACQ138,April,2015,Advertising,USA,4.790000e+08,Twitter
883,ACQ127,July,2015,"Computer vision, augmented reality",ISR,6.000000e+07,Facebook
884,ACQ126,July,2015,Cloud security,ISR,3.200000e+08,Microsoft
887,ACQ123,July,2015,Clothing E-commerce website,USA,1.600000e+08,Yahoo
889,ACQ121,August,2015,Healthcare imaging software,USA,1.000000e+09,IBM
911,ACQ101,November,2015,Object-based storage software,USA,1.309000e+09,IBM
915,AcQ916,June,2018,Version Control Hosting,USA,7.500000e+09,Microsoft

In [13]:
x=data1.iloc[:,:6]

In [14]:
x

,AcquisitionID,AcquisitionMonth,AcquisitionYear,Business,Country,Value (USD)
0,ACQ99,November,2015,Cloud software,USA,3.800000e+08
8,ACQ915,July,1987,Computer software,USA,1.400000e+07
28,ACQ898,January,1996,Software,USA,1.330000e+08
32,ACQ894,April,1996,Computer software,USA,1.415000e+07
36,ACQ890,February,1997,Internet software,USA,2.000000e+07
38,ACQ889,February,1997,Unix-like hardware and software platform,USA,4.040000e+08
40,ACQ887,April,1997,Internet service provider,USA,4.250000e+08
45,ACQ882,September,1997,Web search engine,USA,1.400000e+06
46,ACQ881,September,1997,Macintosh clones,USA,1.100000e+08
47,ACQ880,October,1997,Web-based email,USA,9.200000e+07
49,ACQ879,December,1997,Internet software,USA,5.000000e+08
52,ACQ876,April,1998,Relationship management software,USA,4.000000e+07
55,ACQ873,June,1998,Web application,USA,4.860000e+07
56,ACQ872,July,1998,Calendaring software,USA,2.100000e+07
58,ACQ870,October,1998,Direct marketing,USA,2.960000e+07
60,ACQ869,November,1998,Internet advertising network,USA,2.650000e+08
61,ACQ868,December,1998,Data analysis,USA,8.100000e+06
62,ACQ867,January,1999,Software,UK,4.926000e+06
66,ACQ863,April,1999,Internet radio,USA,5.700000e+09
69,ACQ860,May,1999,Internet service provider,USA,1.300000e+08
70,ACQ86,February,2016,"SwiftKey, a keyboard productivity application",UK,2.500000e+08
71,ACQ859,May,1999,Web hosting service,USA,3.600000e+09
72,ACQ858,June,1999,Content delivery network,USA,8.000000e+07
75,ACQ855,June,1999,Defect detection software,USA,5.890000e+07
76,ACQ854,July,1999,Application software,SWE,1.254200e+08
82,ACQ849,November,1999,Computer graphic chips,USA,1.500000e+07
83,ACQ848,January,2000,Wholesale drawing software,USA,1.375000e+09
86,ACQ845,March,2000,Internet service provider,USA,8.975000e+07
90,ACQ841,April,2000,Cable television,USA,9.448000e+08
93,ACQ839,June,2000,E-commerce,USA,8.900000e+06
...,...,...,...,...,...,...
745,ACQ251,January,2014,Artificial intelligence,UK,6.250000e+08
752,ACQ245,February,2014,Mobile messaging,USA,1.900000e+10
758,ACQ24,June,2017,Cloud Business Management,ISR,5.000000e+07
759,ACQ239,March,2014,Virtual reality technology,USA,2.000000e+09
760,ACQ238,March,2014,High-altitude UAVs,UK,2.000000e+07
766,ACQ232,April,2014,Data reseller,USA,1.340000e+08
781,ACQ219,June,2014,Mobile app install ads,USA,1.000000e+08
782,ACQ218,June,2014,Native mobile advertising,USA,5.000000e+07
784,ACQ216,June,2014,Satellite,USA,5.000000e+08
789,ACQ211,June,2014,Home monitoring,USA,5.550000e+08
793,ACQ208,June,2014,Music streaming,USA,3.000000e+07
799,ACQ202,July,2014,Mobile Analytics,USA,2.000000e+08
806,ACQ197,August,2014,"Headphones, music streaming (Beats Music)",USA,3.000000e+09
814,ACQ19,September,2017,Talent and intellectual property licenses,TWN,1.100000e+09
822,ACQ182,September,2014,Document Handling,IND,1.500000e+07
825,ACQ18,September,2017,Augmented reality head-mounted display,CAN,3.000000e+07
830,ACQ175,November,2014,Video games,SWE,2.500000e+09
831,ACQ174,November,2014,Online Video Advertising,USA,6.400000e+08
845,ACQ161,January,2015,Music analytics,UK,5.000000e+07
848,ACQ159,February,2015,Sunrise Calendar applications,USA,1.000000e+08
852,ACQ155,February,2015,Styli and pen input hardware and software,ISR,2.000000e+08
856,ACQ151,March,2015,Live-Video Streaming,USA,1.000000e+08
867,ACQ141,April,2015,Camera,ISR,2.000000e+07
871,ACQ138,April,2015,Advertising,USA,4.790000e+08
883,ACQ127,July,2015,"Computer vision, augmented reality",ISR,6.000000e+07
884,ACQ126,July,2015,Cloud security,ISR,3.200000e+08
887,ACQ123,July,2015,Clothing E-commerce website,USA,1.600000e+08
889,ACQ121,August,2015,Healthcare imaging software,USA,1.000000e+09
911,ACQ101,November,2015,Object-based storage software,USA,1.309000e+09
915,AcQ916,June,2018,Version Control Hosting,USA,7.500000e+09

In [15]:
y=data1.iloc[:,-1:]

In [16]:
y

    ParentCompany
0          Google
8       Microsoft
28      Microsoft
32      Microsoft
36      Microsoft
38          Apple
40      Microsoft
45          Yahoo
46          Apple
47          Yahoo
49      Microsoft
52      Microsoft
55          Yahoo
56          Yahoo
58          Yahoo
60      Microsoft
61          Yahoo
62          Apple
66          Yahoo
69          Yahoo
70      Microsoft
71          Yahoo
72          Yahoo
75      Microsoft
76      Microsoft
82          Apple
83      Microsoft
86      Microsoft
90      Microsoft
93          Yahoo
..            ...
745        Google
752      Facebook
758     Microsoft
759      Facebook
760      Facebook
766       Twitter
781       Twitter
782       Twitter
784        Google
789        Google
793         Apple
799         Yahoo
806         Apple
814        Google
822         Yahoo
825         Apple
830     Microsoft
831         Yahoo
845         Apple
848     Microsoft
852     Microsoft
856       Twitter
867         Apple
871       Twitter
883      Facebook
884     Microsoft
887         Yahoo
889           IBM
911           IBM
915     Microsoft

[245 rows x 1 columns]

In [17]:
x.shape

(245, 6)

In [18]:
y.shape

(245, 1)

In [19]:
from sklearn.preprocessing import LabelEncoder
le0 = LabelEncoder()
x.iloc[:,0] = le0.fit_transform(x.iloc[:,0])

class MultiColumnLabelEncoder:
    def __init__(self,columns = None):
        self.columns = columns # array of column names to encode

    def fit(self,X,y=None):
        return self # not relevant here

    def transform(self,X):
        '''
        Transforms columns of X specified in self.columns using
        LabelEncoder(). If no columns specified, transforms all
        columns in X.
        '''
        output = X.copy()
        if self.columns is not None:
            for col in self.columns:
                output[col] = LabelEncoder().fit_transform(output[col])
        else:
            for colname,col in output.iteritems():
                output[colname] = LabelEncoder().fit_transform(col)
        return output

    def fit_transform(self,X,y=None):
        return self.fit(X,y).transform(X)

encoding_pipeline = Pipeline([('encoding',MultiColumnLabelEncoder(columns=['fruit','color']))])
encoding_pipeline.fit_transform(fruit_data)

In [20]:
x.iloc[:,0]

0      243
8      242
28     241
32     240
36     239
38     238
40     237
45     236
46     235
47     234
49     233
52     232
55     231
56     230
58     229
60     228
61     227
62     226
66     225
69     224
70     223
71     222
72     221
75     220
76     219
82     218
83     217
86     216
90     215
93     214
      ...
745     28
752     27
758     26
759     25
760     24
766     23
781     22
782     21
784     20
789     19
793     18
799     17
806     16
814     15
822     14
825     13
830     12
831     11
845     10
848      9
852      8
856      7
867      6
871      5
883      4
884      3
887      2
889      1
911      0
915    244
Name: AcquisitionID, Length: 245, dtype: int64

In [21]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
x.iloc[:,1] = le1.fit_transform(x.iloc[:,1])

In [22]:
x.iloc[:,1]

0      10
8       6
28      5
32      0
36      3
38      3
40      0
45     12
46     12
47     11
49      2
52      0
55      7
56      6
58     11
60     10
61      2
62      5
66      0
69      9
70      3
71      9
72      7
75      7
76      6
82     10
83      5
86      8
90      0
93      7
       ..
745     5
752     3
758     7
759     8
760     8
766     0
781     7
782     7
784     7
789     7
793     7
799     6
806     1
814    12
822    12
825    12
830    10
831    10
845     5
848     3
852     3
856     8
867     0
871     0
883     6
884     6
887     6
889     1
911    10
915     7
Name: AcquisitionMonth, Length: 245, dtype: int64

In [23]:
from sklearn.preprocessing import LabelEncoder
le3 = LabelEncoder()
x.iloc[:,3] = le3.fit_transform(x.iloc[:,3])

In [24]:
x.iloc[:,3]

0       38
8       43
28     172
32      43
36      97
38     189
40      96
45     210
46     102
47     211
49      97
52     150
55     204
56      29
58      64
60      93
61      54
62     172
66      95
69      96
70     183
71     208
72      45
75      59
76      12
82      42
83     213
86      96
90      28
93      67
      ...
745     13
752    117
758     34
759    200
760     83
766     56
781    114
782    124
784    155
789     85
793    123
799    108
806     81
814    184
822     65
825     16
830    194
831    131
845    121
848    182
852    181
856     99
867     30
871      4
883     44
884     37
887     33
889     82
911    129
915    190
Name: Business, Length: 245, dtype: int64

In [25]:
from sklearn.preprocessing import LabelEncoder
le4 = LabelEncoder()
x.iloc[:,4] = le4.fit_transform(x.iloc[:,4])

In [26]:
x.iloc[:,4]

0      19
8      19
28     19
32     19
36     19
38     19
40     19
45     19
46     19
47     19
49     19
52     19
55     19
56     19
58     19
60     19
61     19
62     17
66     19
69     19
70     17
71     19
72     19
75     19
76     14
82     19
83     19
86     19
90     19
93     19
       ..
745    17
752    19
758    10
759    19
760    17
766    19
781    19
782    19
784    19
789    19
793    19
799    19
806    19
814    16
822     9
825     1
830    14
831    19
845    17
848    19
852    10
856    19
867    10
871    19
883    10
884    10
887    19
889    19
911    19
915    19
Name: Country, Length: 245, dtype: int64

In [27]:
from sklearn.preprocessing import LabelEncoder
le5 = LabelEncoder()
x.iloc[:,5] = le5.fit_transform(x.iloc[:,5])

In [28]:
x.iloc[:,5]

0       94
8       16
28      66
32      17
36      22
38      98
40      99
45       2
46      58
47      54
49     108
52      34
55      37
56      23
58      29
60      81
61      10
62       5
66     145
69      65
70      80
71     143
72      50
75      41
76      63
82      19
83     129
86      53
90     120
93      12
      ...
745    111
752    151
758     38
759    135
760     22
766     67
781     56
782     38
784    108
789    109
793     30
799     77
806    139
814    123
822     19
825     30
830    137
831    112
845     38
848     56
852     77
856     56
867     22
871    105
883     42
884     87
887     71
889    122
911    127
915    148
Name: Value (USD), Length: 245, dtype: int64

In [29]:
from sklearn.preprocessing import LabelEncoder
ley0 = LabelEncoder()
y.iloc[:,0] = ley0.fit_transform(y.iloc[:,0])

In [30]:
y.iloc[:,0]

0      2
8      4
28     4
32     4
36     4
38     0
40     4
45     6
46     0
47     6
49     4
52     4
55     6
56     6
58     6
60     4
61     6
62     0
66     6
69     6
70     4
71     6
72     6
75     4
76     4
82     0
83     4
86     4
90     4
93     6
      ..
745    2
752    1
758    4
759    1
760    1
766    5
781    5
782    5
784    2
789    2
793    0
799    6
806    0
814    2
822    6
825    0
830    4
831    6
845    0
848    4
852    4
856    5
867    0
871    5
883    1
884    4
887    6
889    3
911    3
915    4
Name: ParentCompany, Length: 245, dtype: int64

In [31]:
y=y.astype('int')

In [32]:
from sklearn.model_selection import train_test_split                                                                                                                    
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.3 , random_state = 0)

In [33]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(random_state=0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [34]:
#x.iloc[:,0]=le.inverse_transform(x.iloc[:,0])

In [35]:
x_test

,AcquisitionID,AcquisitionMonth,AcquisitionYear,Business,Country,Value (USD)
318,151,0,2007,87,15,104
871,5,0,2015,4,19,105
212,170,9,2005,31,3,19
142,188,2,2002,134,19,55
610,62,1,2012,86,19,130
649,54,8,2013,90,19,22
456,106,9,2010,192,19,45
455,107,9,2010,92,19,34
375,136,8,2008,153,19,6
169,179,0,2004,18,9,74
667,49,7,2013,35,19,135
415,120,1,2009,170,19,36
308,154,3,2007,89,19,25
831,11,10,2014,131,19,112
688,44,1,2013,49,10,122
507,90,5,2011,51,0,34
616,61,11,2012,74,18,35
598,67,7,2012,73,10,56
224,169,1,2005,118,19,38
361,139,5,2008,72,10,86
380,132,0,2008,53,19,77
120,198,3,2002,98,19,101
167,180,8,2004,145,5,110
650,53,8,2013,128,17,30
420,118,10,2009,202,19,30
605,64,6,2012,140,19,92
431,114,5,2010,111,19,84
46,235,12,1997,102,19,58
784,20,7,2014,155,19,108
333,147,7,2007,127,19,77
...,...,...,...,...,...,...
208,172,0,2005,69,19,123
479,99,1,2010,104,19,106
377,135,0,2008,71,14,116
66,225,0,1999,95,19,145
378,134,0,2008,138,19,48
60,228,10,1998,93,19,81
521,85,0,2011,149,19,22
45,236,12,1997,210,19,2
524,84,9,2011,185,12,149
714,36,9,2017,13,19,77
501,91,10,2010,7,19,11
520,86,0,2011,188,19,113
369,137,3,2008,195,19,71
413,121,1,2009,193,19,66
290,160,11,2006,197,19,133
102,210,3,2001,133,0,30
464,104,7,2010,4,19,51
541,81,1,2011,0,14,82
334,146,6,2007,202,19,35
915,244,7,2018,190,19,148
315,153,0,2007,132,19,140
766,23,0,2014,56,19,67
852,8,3,2015,181,10,77
712,37,10,2013,180,10,90
793,18,7,2014,123,19,30
61,227,2,1998,54,19,10
550,77,12,2011,130,8,59
565,73,2,2011,39,19,102
239,167,10,2005,107,0,4
36,239,3,1997,97,19,22

In [36]:
x_train.iloc[:,0]=le0.inverse_transform(x_train.iloc[:,0])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [37]:
x_train.iloc[:,0]

379    ACQ581
158    ACQ780
400    ACQ562
135    ACQ800
183    ACQ758
83     ACQ848
708    ACQ285
577    ACQ402
759    ACQ239
113    ACQ820
56     ACQ872
32     ACQ894
344    ACQ612
76     ACQ854
95     ACQ837
760    ACQ238
155    ACQ783
143    ACQ794
626    ACQ359
395    ACQ567
69     ACQ860
653    ACQ334
434    ACQ531
138    ACQ799
673    ACQ316
257    ACQ691
130    ACQ805
416    ACQ548
558     ACQ42
781    ACQ219
        ...
390    ACQ571
489    ACQ482
867    ACQ141
210    ACQ733
240    ACQ706
82     ACQ849
549    ACQ428
259     ACQ69
825     ACQ18
583    ACQ398
845    ACQ161
111    ACQ822
663    ACQ325
149    ACQ789
468    ACQ500
304    ACQ649
752    ACQ245
202    ACQ740
301    ACQ651
108    ACQ825
71     ACQ859
737    ACQ259
47     ACQ880
349    ACQ608
668    ACQ320
192     ACQ75
655    ACQ332
396    ACQ566
122    ACQ812
575    ACQ404
Name: AcquisitionID, Length: 171, dtype: object

In [38]:
x_train.iloc[:,1]=le1.inverse_transform(x_train.iloc[:,1])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [39]:
x_train.iloc[:,1]

379        April
158       August
400    September
135    September
183    September
83       January
708      October
577     February
759        March
113         July
56          July
32         April
344    September
76          July
95        August
760        March
155         June
143     December
626     November
395         July
69           May
653        April
434     February
138      October
673         July
257     Feburary
130         July
416       August
558     December
781         June
         ...
390         June
489    September
867        April
210          May
240     December
82      November
549    September
259         June
825    September
583        April
845      January
111         June
663          May
149        April
468         July
304     December
752     February
202        March
301     December
108          May
71           May
737      January
47       October
349    September
668         June
192        March
655        April
396         July
122        April
575      January
Name: AcquisitionMonth, Length: 171, dtype: object

In [40]:
x_train.iloc[:,3]=le3.inverse_transform(x_train.iloc[:,3])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [41]:
x_train.iloc[:,3]

379                             Mobile Internet software
158                                             Software
400                       Search and e-commerce services
135                             Software and video games
183                                         Audio player
83                            Wholesale drawing software
708                         DroidBooster App for Android
577                                    App search engine
759                           Virtual reality technology
113                                    Database Software
56                                  Calendaring software
32                                     Computer software
344                                  Advertising network
76                                  Application software
95                               Electronic mailing list
760                                   High-altitude UAVs
155                              Search engine marketing
143                            Internet service provider
626                                     Package delivery
395                    Business Rules Management Systems
69                             Internet service provider
653                          Natural Language Processing
434                                        Social search
138          Business Consulting and Technology Services
673                           Automated Video Production
257                                   Network management
130                                 Software programming
416                                         Social media
558                      Professional Networking Service
781                               Mobile app install ads
                             ...
390                                    Social networking
489                                   Facial recognition
867                                               Camera
210                                            Messaging
240                                   Social bookmarking
82                                Computer graphic chips
549                                   Restaurant reviews
259    Advanced Video Upscaling, Compression and Enha...
825               Augmented reality head-mounted display
583                                        Photo sharing
845                                      Music analytics
111                                   Online music store
663                                             Blogging
149                                   Online advertising
468                               Travel recommendations
304                                              Mapping
752                                     Mobile messaging
202                                Image hosting service
301                                    Virtual community
108                                    Internet software
71                                   Web hosting service
737                            Customer service software
47                                       Web-based email
349                               Collaborative software
668                              GPS navigation software
192    Salesforce systems integrator and professional...
655                                  Mobile app backends
396                                         Online video
122                          FireWire chips and software
575                            Software Development Firm
Name: Business, Length: 171, dtype: object

In [42]:
x_train.iloc[:,4]=le4.inverse_transform(x_train.iloc[:,4])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [43]:
x_train.iloc[:,4]

379    USA
158    USA
400    USA
135     UK
183    USA
83     USA
708    FRA
577    USA
759    USA
113    USA
56     USA
32     USA
344    USA
76     SWE
95     USA
760     UK
155    USA
143    USA
626    CAN
395    FRA
69     USA
653    USA
434    USA
138    USA
673    USA
257    USA
130    DEN
416    JOR
558    USA
781    USA
      ...
390    USA
489    SWE
867    ISR
210    USA
240    USA
82     USA
549    USA
259     UK
825    CAN
583    USA
845     UK
111    USA
663    USA
149    USA
468    USA
304    CHE
752    USA
202    CAN
301    TWN
108    CAN
71     USA
737    USA
47     USA
349    USA
668    ISR
192    USA
655    USA
396    USA
122    USA
575    ISR
Name: Country, Length: 171, dtype: object

In [44]:
x_train.iloc[:,5]=le5.inverse_transform(x_train.iloc[:,5])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [45]:
x_train.iloc[:,5]

379    5.000000e+08
158    4.500000e+05
400    4.860000e+08
135    3.750000e+08
183    1.600000e+08
83     1.375000e+09
708    2.300000e+07
577    5.000000e+07
759    2.000000e+09
113    1.000000e+09
56     2.100000e+07
32     1.415000e+07
344    3.000000e+08
76     1.254200e+08
95     4.320000e+08
760    2.000000e+07
155    1.630000e+09
143    2.350000e+08
626    1.700000e+07
395    3.400000e+08
69     1.300000e+08
653    3.000000e+07
434    5.000000e+07
138    3.500000e+09
673    5.000000e+07
257    8.650000e+08
130    1.330000e+09
416    1.670000e+08
558    2.620000e+10
781    1.000000e+08
           ...
390    3.100000e+07
489    2.900000e+07
867    2.000000e+07
210    7.000000e+06
240    2.000000e+07
82     1.500000e+07
549    1.510000e+08
259    1.500000e+08
825    3.000000e+07
583    1.000000e+09
845    5.000000e+07
111    1.200000e+07
663    1.100000e+09
149    1.020000e+08
468    2.500000e+06
304    2.800000e+07
752    1.900000e+10
202    4.000000e+07
301    2.200000e+07
108    3.600000e+07
71     3.600000e+09
737    1.000000e+08
47     9.200000e+07
349    3.500000e+08
668    9.660000e+08
192    2.000000e+08
655    8.500000e+07
396    1.500000e+07
122    1.300000e+07
575    7.000000e+07
Name: Value (USD), Length: 171, dtype: float64

In [46]:
y_train.iloc[:,-1:]=ley0.inverse_transform(y_train.iloc[:,-1:])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [47]:
y_train.iloc[:,-1:]

    ParentCompany
379     Microsoft
158     Microsoft
400     Microsoft
135     Microsoft
183         Yahoo
83      Microsoft
708        Google
577         Apple
759      Facebook
113           IBM
56          Yahoo
32      Microsoft
344         Yahoo
76      Microsoft
95          Yahoo
760      Facebook
155         Yahoo
143         Yahoo
626        Google
395           IBM
69          Yahoo
653        Google
434        Google
138           IBM
673         Yahoo
257           IBM
130     Microsoft
416         Yahoo
558     Microsoft
781       Twitter
..            ...
390      Facebook
489         Apple
867         Apple
210     Microsoft
240         Yahoo
82          Apple
549        Google
259       Twitter
825         Apple
583      Facebook
845         Apple
111         Yahoo
663         Yahoo
149        Google
468      Facebook
304        Google
752      Facebook
202         Yahoo
301         Yahoo
108     Microsoft
71          Yahoo
737     Microsoft
47          Yahoo
349         Yahoo
668        Google
192           IBM
655      Facebook
396        Google
122         Apple
575           IBM

[171 rows x 1 columns]

In [48]:
x_test

,AcquisitionID,AcquisitionMonth,AcquisitionYear,Business,Country,Value (USD)
318,151,0,2007,87,15,104
871,5,0,2015,4,19,105
212,170,9,2005,31,3,19
142,188,2,2002,134,19,55
610,62,1,2012,86,19,130
649,54,8,2013,90,19,22
456,106,9,2010,192,19,45
455,107,9,2010,92,19,34
375,136,8,2008,153,19,6
169,179,0,2004,18,9,74
667,49,7,2013,35,19,135
415,120,1,2009,170,19,36
308,154,3,2007,89,19,25
831,11,10,2014,131,19,112
688,44,1,2013,49,10,122
507,90,5,2011,51,0,34
616,61,11,2012,74,18,35
598,67,7,2012,73,10,56
224,169,1,2005,118,19,38
361,139,5,2008,72,10,86
380,132,0,2008,53,19,77
120,198,3,2002,98,19,101
167,180,8,2004,145,5,110
650,53,8,2013,128,17,30
420,118,10,2009,202,19,30
605,64,6,2012,140,19,92
431,114,5,2010,111,19,84
46,235,12,1997,102,19,58
784,20,7,2014,155,19,108
333,147,7,2007,127,19,77
...,...,...,...,...,...,...
208,172,0,2005,69,19,123
479,99,1,2010,104,19,106
377,135,0,2008,71,14,116
66,225,0,1999,95,19,145
378,134,0,2008,138,19,48
60,228,10,1998,93,19,81
521,85,0,2011,149,19,22
45,236,12,1997,210,19,2
524,84,9,2011,185,12,149
714,36,9,2017,13,19,77
501,91,10,2010,7,19,11
520,86,0,2011,188,19,113
369,137,3,2008,195,19,71
413,121,1,2009,193,19,66
290,160,11,2006,197,19,133
102,210,3,2001,133,0,30
464,104,7,2010,4,19,51
541,81,1,2011,0,14,82
334,146,6,2007,202,19,35
915,244,7,2018,190,19,148
315,153,0,2007,132,19,140
766,23,0,2014,56,19,67
852,8,3,2015,181,10,77
712,37,10,2013,180,10,90
793,18,7,2014,123,19,30
61,227,2,1998,54,19,10
550,77,12,2011,130,8,59
565,73,2,2011,39,19,102
239,167,10,2005,107,0,4
36,239,3,1997,97,19,22

In [49]:
x_test.iloc[:,0]=le0.inverse_transform(x_test.iloc[:,0])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [50]:
x_test.iloc[:,0]

318    ACQ636
871    ACQ138
212    ACQ731
142    ACQ795
610    ACQ373
649    ACQ338
456    ACQ511
455    ACQ512
375    ACQ585
169    ACQ770
667    ACQ321
415    ACQ549
308    ACQ645
831    ACQ174
688    ACQ302
507    ACQ466
616    ACQ368
598    ACQ384
224    ACQ720
361    ACQ598
380    ACQ580
120    ACQ814
167    ACQ772
650    ACQ337
420    ACQ544
605    ACQ378
431    ACQ534
46     ACQ881
784    ACQ216
333    ACQ622
        ...
208    ACQ735
479    ACQ491
377    ACQ583
66     ACQ863
378    ACQ582
60     ACQ869
521    ACQ453
45     ACQ882
524    ACQ450
714     ACQ28
501    ACQ471
520    ACQ454
369    ACQ590
413    ACQ550
290    ACQ661
102    ACQ830
464    ACQ504
541    ACQ435
334    ACQ621
915    AcQ916
315    ACQ639
766    ACQ232
852    ACQ155
712    ACQ281
793    ACQ208
61     ACQ868
550    ACQ427
565    ACQ413
239    ACQ707
36     ACQ890
Name: AcquisitionID, Length: 74, dtype: object

In [51]:
x_test.iloc[:,1]=le1.inverse_transform(x_test.iloc[:,1])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [52]:
x_test.iloc[:,1]

318        April
871        April
212          May
142     December
610       August
649        March
456          May
455          May
375        March
169        April
667         June
415       August
308     February
831     November
688       August
507      January
616      October
598         June
224       August
361      January
380        April
120     February
167        March
650        March
420     November
605         July
431      January
46     September
784         June
333         June
         ...
208        April
479       August
377        April
66         April
378        April
60      November
521        April
45     September
524          May
714          May
501     November
520        April
369     February
413       August
290      October
102     February
464         June
541       August
334         July
915         June
315        April
766        April
852     February
712     November
793         June
61      December
550    September
565     December
239     November
36      February
Name: AcquisitionMonth, Length: 74, dtype: object

In [53]:
x_test.iloc[:,3]=le3.inverse_transform(x_test.iloc[:,3])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [54]:
x_test.iloc[:,3]

318                                  IT Services
871                                  Advertising
212                               Certain assets
142                   Online enterprise location
610                      Human Capital Solutions
649                              Indoor location
456                  Video and audio compression
455                Intellectual property/patents
375                    Rootkit security software
169                                 BPO Services
667               Cloud Computing Infrastructure
415                 Social networking aggregator
308                          In-game advertising
831                     Online Video Advertising
688                               Cyber Security
507                                  Daily deals
616                           Facial recognition
598                    Face recognition platform
224                      Mobile operating system
361                           Enterprise storage
380                          Data De-duplication
120                            Job search engine
167                     Price comparison service
650              News aggregation, summarization
420                                Voice over IP
605              PC and mobile security products
431                           Mobile advertising
46                              Macintosh clones
784                                    Satellite
333                                   Networking
                         ...
208           Enterprise Information Integration
479                  Marketing planning software
377              Enterprise software development
66                                Internet radio
378                       Online search software
60                  Internet advertising network
521                         Recognize TV content
45                             Web search engine
524                           Telecommunications
714                      Artificial intelligence
501              American Farm Bureau Federation
520                            Travel technology
369                              Video on demand
413                            Video compression
290                                Video sharing
102                         Online auction tools
464                                  Advertising
541                                   3D mapping
334                                Voice over IP
915                      Version Control Hosting
315                           Online advertising
766                                Data reseller
852    Styli and pen input hardware and software
712                 Structured-light 3D scanners
793                              Music streaming
61                                 Data analysis
550                       One deal a day service
565                 Cloud-based Retail Analytics
239                                       Mobile
36                             Internet software
Name: Business, Length: 74, dtype: object

In [55]:
x_test.iloc[:,4]=le4.inverse_transform(x_test.iloc[:,4])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [56]:
x_test.iloc[:,4]

318    SWI
871    USA
212    CHN
142    USA
610    USA
649    USA
456    USA
455    USA
375    USA
169    IND
667    USA
415    USA
308    USA
831    USA
688    ISR
507    AUS
616    UKR
598    ISR
224    USA
361    ISR
380    USA
120    USA
167     EU
650     UK
420    USA
605    USA
431    USA
46     USA
784    USA
333    USA
      ...
208    USA
479    USA
377    SWE
66     USA
378    USA
60     USA
521    USA
45     USA
524    LUX
714    USA
501    USA
520    USA
369    USA
413    USA
290    USA
102    AUS
464    USA
541    SWE
334    USA
915    USA
315    USA
766    USA
852    ISR
712    ISR
793    USA
61     USA
550    GER
565    USA
239    AUS
36     USA
Name: Country, Length: 74, dtype: object

In [57]:
x_test.iloc[:,5]=le5.inverse_transform(x_test.iloc[:,5])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [58]:
x_test.iloc[:,5]

318    4.600000e+08
871    4.790000e+08
212    1.500000e+07
142    9.584900e+07
610    1.400000e+09
649    2.000000e+07
456    6.820000e+07
455    4.000000e+07
375    5.000000e+06
169    1.700000e+08
667    2.000000e+09
415    4.750000e+07
308    2.300000e+07
831    6.400000e+08
688    1.000000e+09
507    4.000000e+07
616    4.500000e+07
598    1.000000e+08
224    5.000000e+07
361    3.000000e+08
380    2.000000e+08
120    4.360000e+08
167    5.790000e+08
650    3.000000e+07
420    3.000000e+07
605    3.560000e+08
431    2.750000e+08
46     1.100000e+08
784    5.000000e+08
333    2.000000e+08
           ...
208    1.100000e+09
479    4.800000e+08
377    8.450000e+08
66     5.700000e+09
378    7.500000e+07
60     2.650000e+08
521    2.000000e+07
45     1.400000e+06
524    8.500000e+09
714    2.000000e+08
501    8.500000e+06
520    6.760000e+08
369    1.600000e+08
413    1.330000e+08
290    1.650000e+09
102    3.000000e+07
464    8.100000e+07
541    2.670000e+08
334    4.500000e+07
915    7.500000e+09
315    3.100000e+09
766    1.340000e+08
852    2.000000e+08
712    3.450000e+08
793    3.000000e+07
61     8.100000e+06
550    1.140000e+08
565    4.400000e+08
239    3.153000e+06
36     2.000000e+07
Name: Value (USD), Length: 74, dtype: float64

In [59]:
y_test.iloc[:,-1:]=ley0.inverse_transform(y_test.iloc[:,-1:])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [60]:
y_test.iloc[:,-1:]

    ParentCompany
318           IBM
871       Twitter
212     Microsoft
142     Microsoft
610           IBM
649         Apple
456        Google
455      Facebook
375     Microsoft
169           IBM
667           IBM
415      Facebook
308        Google
831         Yahoo
688           IBM
507         Yahoo
616        Google
598      Facebook
224        Google
361           IBM
380           IBM
120         Yahoo
167         Yahoo
650         Yahoo
420        Google
605         Apple
431         Apple
46          Apple
784        Google
333     Microsoft
..            ...
208           IBM
479           IBM
377           IBM
66          Yahoo
378     Microsoft
60      Microsoft
521         Yahoo
45          Yahoo
524     Microsoft
714         Apple
501      Facebook
520        Google
369         Yahoo
413        Google
290        Google
102         Yahoo
464        Google
541         Apple
334        Google
915     Microsoft
315        Google
766       Twitter
852     Microsoft
712         Apple
793         Apple
61          Yahoo
550        Google
565           IBM
239     Microsoft
36      Microsoft

[74 rows x 1 columns]

In [69]:
new=LabelEncoder().fit_transform(['ACQ636','April',2015,'IT Services','SWI','4.600000e+08'])

In [70]:
new

array([2, 3, 0, 4, 5, 1], dtype=int64)

In [63]:
pd.DataFrame(new)

   0
0  1
1  2
2  3
3  4
4  0

In [71]:
y_predict =classifier.predict([new])

In [74]:
y_predict=pd.DataFrame(y_predict)

In [81]:
y_test

    ParentCompany
318           IBM
871       Twitter
212     Microsoft
142     Microsoft
610           IBM
649         Apple
456        Google
455      Facebook
375     Microsoft
169           IBM
667           IBM
415      Facebook
308        Google
831         Yahoo
688           IBM
507         Yahoo
616        Google
598      Facebook
224        Google
361           IBM
380           IBM
120         Yahoo
167         Yahoo
650         Yahoo
420        Google
605         Apple
431         Apple
46          Apple
784        Google
333     Microsoft
..            ...
208           IBM
479           IBM
377           IBM
66          Yahoo
378     Microsoft
60      Microsoft
521         Yahoo
45          Yahoo
524     Microsoft
714         Apple
501      Facebook
520        Google
369         Yahoo
413        Google
290        Google
102         Yahoo
464        Google
541         Apple
334        Google
915     Microsoft
315        Google
766       Twitter
852     Microsoft
712         Apple
793         Apple
61          Yahoo
550        Google
565           IBM
239     Microsoft
36      Microsoft

[74 rows x 1 columns]

In [78]:
y_predict.shape

(1, 1)

In [88]:
x_test_pred=LabelEncoder().fit_transform(x_test.iloc[:,3])

In [96]:
x_test_pred=pd.DataFrame(x_test_pred)

In [98]:
x_test_pred

     0
0   23
1    2
2    7
3   46
4   22
5   25
6   63
7   26
8   51
9    5
10   8
11  55
12  24
13  43
14  12
15  13
16  21
17  20
18  38
19  19
20  14
21  31
22  49
23  41
24  67
25  48
26  37
27  33
28  52
29  40
..  ..
44  17
45  34
46  18
47  29
48  47
49  27
50  50
51  69
52  59
53   4
54   3
55  60
56  65
57  64
58  66
59  45
60   2
61   0
62  67
63  62
64  44
65  16
66  58
67  57
68  39
69  15
70  42
71   9
72  35
73  30

[74 rows x 1 columns]

In [100]:
pred_y=classifier.predict((x_test_pred))

ValueError: Number of features of the model must match the input. Model n_features is 6 and input n_features is 1

In [95]:
y_test

    ParentCompany
318           IBM
871       Twitter
212     Microsoft
142     Microsoft
610           IBM
649         Apple
456        Google
455      Facebook
375     Microsoft
169           IBM
667           IBM
415      Facebook
308        Google
831         Yahoo
688           IBM
507         Yahoo
616        Google
598      Facebook
224        Google
361           IBM
380           IBM
120         Yahoo
167         Yahoo
650         Yahoo
420        Google
605         Apple
431         Apple
46          Apple
784        Google
333     Microsoft
..            ...
208           IBM
479           IBM
377           IBM
66          Yahoo
378     Microsoft
60      Microsoft
521         Yahoo
45          Yahoo
524     Microsoft
714         Apple
501      Facebook
520        Google
369         Yahoo
413        Google
290        Google
102         Yahoo
464        Google
541         Apple
334        Google
915     Microsoft
315        Google
766       Twitter
852     Microsoft
712         Apple
793         Apple
61          Yahoo
550        Google
565           IBM
239     Microsoft
36      Microsoft

[74 rows x 1 columns]

In [93]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,classifier.predict(([x_test_pred])))

ValueError: Number of features of the model must match the input. Model n_features is 6 and input n_features is 74